apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: An example of a Backstage application.
  # Example for optional annotations
  annotations:
    github.com/project-slug: backstage/backstage
    backstage.io/techdocs-ref: dir:.
  'backstage.io/kubernetes-namespace': ingress-nginx
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental
